// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJZq-8YwhB727bMa9mC35pXjKge_sGzio',
    appId: '1:917533419040:web:cc09ba2b7082c9201a7e45',
    messagingSenderId: '917533419040',
    projectId: 'project-1-105ab',
    authDomain: 'project-1-105ab.firebaseapp.com',
    storageBucket: 'project-1-105ab.appspot.com',
    measurementId: 'G-W798KF28E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pVDhpXtDlzxjAs_BSrm_Oi468Ja_mcI',
    appId: '1:917533419040:android:1f5bdd3da6794e451a7e45',
    messagingSenderId: '917533419040',
    projectId: 'project-1-105ab',
    storageBucket: 'project-1-105ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZGps3DkpXI92TKwoSwcu3dwSDc5KIizs',
    appId: '1:917533419040:ios:ee9b50d1fa55a1701a7e45',
    messagingSenderId: '917533419040',
    projectId: 'project-1-105ab',
    storageBucket: 'project-1-105ab.appspot.com',
    iosBundleId: 'com.example.flutterApplication14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZGps3DkpXI92TKwoSwcu3dwSDc5KIizs',
    appId: '1:917533419040:ios:ee9b50d1fa55a1701a7e45',
    messagingSenderId: '917533419040',
    projectId: 'project-1-105ab',
    storageBucket: 'project-1-105ab.appspot.com',
    iosBundleId: 'com.example.flutterApplication14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJZq-8YwhB727bMa9mC35pXjKge_sGzio',
    appId: '1:917533419040:web:2c71b5ca0fa0b9061a7e45',
    messagingSenderId: '917533419040',
    projectId: 'project-1-105ab',
    authDomain: 'project-1-105ab.firebaseapp.com',
    storageBucket: 'project-1-105ab.appspot.com',
    measurementId: 'G-4WJZFQRN9E',
  );

}